files:
  - source: /i18n/fbt/.source_strings.json
    translation: /i18n/fbt/translations/%two_letters_code%/translation.json
    excluded_target_languages:
      - ar
      - be
      - bg
      - ca
      - cs
      - da
      - de
      - el
      - es
      - et
      - eu
      - fi
      - fil
      - fr
      - gd
      - gl
      - gu
      - he
      - hi
      - hr
      - hu
      - id
      - it
      - ja
      - ka
      - kn
      - ko
      - lb
      - lt
      - lv
      - me
      - mi
      - mk
      - ml
      - mr
      - ms
      - nb
      - nl
      - nn
      - pa
      - pl
      - pt
      - ro
      - ru
      - sh
      - si
      - sk
      - sl
      - sq
      - sr
      - sv
      - sw
      - ta
      - te
      - th
      - tl
      - tr
      - uk
      - vi
      - zh
    ]
